server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  liquibase:
    change-log: classpath:liquibase/changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true