server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/postgres
    username: postgres
    password: postgres

  data:
    redis:
      host: localhost
      port: 6379
      password: redis

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

jwt:
  secret: KzViYm9mVWxWY2pMVXFYZldqRmZ5ZWpSc0dPZ25ZV1E=

  access-token-expiration-ms: 900000
  refresh-token-expiration-ms: 604800000

logging:
  level:
    org.springframework.security: DEBUG
